name = "revisor-tom-voz"
main = "worker.js"
compatibility_date = "2026-09-11"

[secrets]
GROQ_API_KEY = "required"
PLUGIN_KEY = "required"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true
